project_id = "hivehr"

[api]
enabled = true
port = 55421
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55432
major_version = 17

[studio]
enabled = true
port = 55423
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 55424

[analytics]
enabled = true
port = 55437

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.hr-api]
verify_jwt = true

[functions.auth-api]
verify_jwt = false

[functions.profile-api]
verify_jwt = true

[functions.employees-api]
verify_jwt = true

[functions.attendance-api]
verify_jwt = true

[functions.policies-api]
verify_jwt = true
